trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: infra_prep
  displayName: "Intrastructure Prep"
  jobs: 
    - job: terraform_deploy
      displayName: "Terraform Deployment"

      steps:
      - task: TerraformInstaller@0
        displayName: "Install Terraform"
        inputs:
          terraformVersion: 'latest'

      - task: TerraformCLI@0
        displayName: "Terraform Init"
        inputs:  
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-template/infra-prep'
          commandOptions: '-backend-config="az_client_id=$(az_client_id)" -backend-config="az_client_secret=$(az_client_secret)" -backend-config="az_subscription_id=$(az_subscription_id)" -backend-config="az_tenant_id=$(az_tenant_id)"'


      - task: TerraformCLI@0
        displayName: "Terraform Plan - infra"
        inputs:
          command: 'plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-template/infra-prep'
          environmentServiceName: 'HBL-MS-AIRS(ce934b07-c047-4954-bfbc-b528d97c2c70)'
          allowTelemetryCollection: false


